name: workspace-grafana-postgres-pgadmin

services:

  ######################################################################
  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:latest
    restart: always
    user: "0"
    tty: true
    environment:
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
    ports:
      - 3000:3000
    volumes:
      - ~/.grafana/grafana-storage:/var/lib/grafana
    networks:
      - postgres

  ######################################################################
  # Postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    user: "0"
    tty: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres/postgresql/data:/var/lib/postgresql/data
    networks:
      - postgres

  ######################################################################
  # PgAdmin
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    user: "0"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - ~/.postgres/pgadmin:/var/lib/pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
    name: postgres
